Updated introduction email
makerspace/makeradmin pull request #173
Opened 2021-09-12 14:11 UTC by philon-

2021-09-12 14:17 UTC, emanuelen5 approved these changes
Grymt!

2021-09-13 17:38 UTC, HalfVoxel requested changes
Nice! Just a tiiny typo.

2021-09-13 17:38 UTC, HalfVoxel commented on api/src/templates/new_member.body.html
> +<p>I mån av plats så kan du lägga ditt projekt i hall-hyllorna i max 3 månader. Ditt projekt ska vara märkt med en etikett från <a href="https://wiki.makerspace.se/Memberbooth">Memberbooth</a>, annar
```suggestion
<p>I mån av plats så kan du lägga ditt projekt i hall-hyllorna i max 3 månader. Ditt projekt ska vara märkt med en etikett från <a href="https://wiki.makerspace.se/Memberbooth">Memberbooth</a>, annars försvinner det. Vi har plats för köpta skivor av plywood, akryl och liknande bredvid laserskäraren i stora rummet. Alla regler kring förvaring på Stockholm Makerspace går att hitta på <a href="https://wiki.makerspace.se/Medlemsf%C3%B6rvaring">wikin.</a></p>
```

2021-09-13 17:38 UTC, HalfVoxel approved these changes
Took the liberty of fixing the typo.

2021-09-13 17:39 UTC, merged